#!/usr/bin/env zsh

# detect operating system
platform=${OSTYPE//[0-9.]/}

# exit shell
alias e="exit"

# clearing shell
alias clr="clear"

# allow sudo of aliases by attempting substitution using ending space
alias sudo="sudo "

# easier navigation
alias ..="cd .."  ## navigate to parent directory
alias ...="cd ../.."  ## navigate to parent of parent directory
alias -- -="cd -"  ## navigate to previous directory

# directory creation
alias md='mkdir -p'  ## create directory hierarchy
alias rd='rmdir -p'  ## delete directory hierarchy, if empty

# ls modifications
if [[ $platform == "linux-gnu" ]]; then
    alias ls="ls -F -h -l --color=auto"  ## ls for non-hidden files
    alias lsa="ls -A -F -h -l --color=auto"  ## almost complete ls
elif [[ $platform == "darwin" ]]; then
    alias ls="ls -F -h -l -G"  ## ls for non-hidden files
    alias lsa="ls -A -F -h -l -G"  ## almost complete ls
fi

# du modifications
alias du="du -h"  ## human friendly du
alias sdu="du -d 1 -h"  # non-recursive du

# map each line
alias map="xargs -n 1"

# coloured grep
alias grep="grep --color=auto"

# find modifications
alias fd="find . -type d -name"  # find directory
alias ff="find . -type f -name"  # find file

# vim modifications
alias v="vim"
alias vr="vim -R"

# human-friendly df
alias df="df -h"

# human-friendly free
alias free="free -h"

# abbreviated git
alias g="git"
