#!/usr/bin/env zsh

# powerlevel10k instant prompt
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# custom settings
source $HOME/.aliases
source $HOME/.exports
source $HOME/.functions
source $HOME/.options
source $HOME/.bindings

# loading antigen
source $HOME/antigen-loader
antigen init $HOME/.antigenrc

# disabling default ls outputs
zstyle ":autocomplete:*" min-input 1

# loading miniconda
source $HOME/miniconda-activations

# enabling powerlevel10k prompt
[[ ! -f $HOME/.p10k.zsh ]] || source $HOME/.p10k.zsh
